name: Swift

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Get swift version
        run: swift --version
      - name: Run tests
        run: |
          swift test
